### ISSUE TITLE
Login does not show editable page

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#13]
1. Login at http://davaz.com/en/personal/life/
2. Login works (no errors).
3. Logged in user can not edit the page.
4. Why?

**Comment by zdavatz** [comment]
I still can edit anything after above commit.

**Comment by zdavatz** [comment]
@ngiger do you have the latest Database from fastpower on your local machine?

**Comment by ngiger** [comment]
Found in the /service/davaz.com/log/main/current the following entries
```
5.8.23.124 - - [12/Mar/2021:09:40:05 +0100] "HEAD / HTTP/1.1" 200 1310 0.0018
[2021-03-12 09:40:05] ERROR Rack::Lint::LintError: Response body was given for HEAD request, but should be empty
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/rack-2.2.3/lib/rack/lint.rb:21:in `assert'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/rack-2.2.3/lib/rack/lint.rb:734:in `verify_content_length'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/rack-2.2.3/lib/rack/lint.rb:762:in `each'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/rack-2.2.3/lib/rack/body_proxy.rb:41:in `method_missing'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/rack-2.2.3/lib/rack/body_proxy.rb:41:in `method_missing'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/rack-2.2.3/lib/rack/lint.rb:754:in `each'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/rack-2.2.3/lib/rack/body_proxy.rb:41:in `method_missing'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:119:in `service'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
>-/var/www/new.davaz.com/vendor/ruby/3.0.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
185.191.171.33 - - [12/Mar/2021:09:42:42 +0100] "GET /en/gallery/art_object/artgroup_id/DES/artobject_id/693 HTTP/1.1" 200 24430 0.0241
```

Why? Did not see this error on my local host.

But will install the latest Database in any case here, too.

**Comment by zdavatz** [comment]
Apache Version on Fastpower ist `2.4.46` this may be related.

**Comment by zdavatz** [comment]
DB dump of today is here: https://github.com/zdavatz/davaz.com/tree/master/db

**Comment by ngiger** [comment]
Found lines like following in `/var/www/new.davaz.com/log/2021/03/15/error_log`
```
[Mon Mar 15 18:20:02.320261 2021] [proxy:error] [pid 3052] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:8007 (*) failed
[Mon Mar 15 18:20:02.320287 2021] [proxy_http:error] [pid 3052] [client 159.226.19.18:42464] AH01114: HTTP: failed to make connection to backend: 127.0.0.1
```

**Comment by zdavatz** [comment]
This is not my IP address, is it yours?

**Comment by ngiger** [comment]
Probably. It just triggered my attention, but does not lead to anything. My adress is 77.57.4.81.
