### ISSUE TITLE
Update Art Object hangs page

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#36]
1. Login as User
2. Goto Art-Object: https://davaz.com/en/works/movies/#1705
3. Update the Art Object.
4. Below Error comes.
5. Log output is: [current.txt](https://github.com/zdavatz/davaz.com/files/8424620/current.txt)

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/209473035-cb0d9839-6923-434e-805a-e56d8a42ecca.png)

**Comment by zdavatz** [comment]
```
@4000000063a8664a10bb4d64 NoMethodError: undefined method `rewind' for #<Rack::Lint::Wrapper::InputWrapper:0x00007f5ffb8f2548 @input=#<Rack::Lint::Wrapper::InputWrapper:0x00007f5ffb8f3c18 @input=#<StringIO:0x00007f5ffb8f9190>>>
@4000000063a8664a10bb5534       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.1/lib/sbsm/session.rb:226:in `block in process_rack'
@4000000063a8664a10bb591c       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.1/lib/sbsm/session.rb:209:in `synchronize'
@4000000063a8664a10bb5d04       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.1/lib/sbsm/session.rb:209:in `process_rack'
@4000000063a8664a10bbd61c       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.1/lib/sbsm/app.rb:135:in `call'
@4000000063a8664a10bbd61c       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/lint.rb:63:in `response'
@4000000063a8664a10bbda04       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/lint.rb:35:in `call'
@4000000063a8664a10bbddec       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/show_exceptions.rb:27:in `call'
@4000000063a8664a10bc2824       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/content_length.rb:20:in `call'
@4000000063a8664a10bc2824       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/static.rb:161:in `call'
@4000000063a8664a10bc5704       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/common_logger.rb:43:in `call'
@4000000063a8664a10bc5704       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/tempfile_reaper.rb:20:in `call'
@4000000063a8664a10bc5aec       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/lint.rb:63:in `response'
@4000000063a8664a10bc5aec       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/lint.rb:35:in `call'
@4000000063a8664a10bc6a8c       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/show_exceptions.rb:27:in `call'
@4000000063a8664a10bc6e74       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/common_logger.rb:43:in `call'
@4000000063a8664a10bc6e74       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.2/lib/rack/content_length.rb:20:in `call'
@4000000063a8664a10bc725c       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/lib/rackup/handler/webrick.rb:94:in `service'
@4000000063a8664a10bc7e14       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
@4000000063a8664a10bc81fc       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
@4000000063a8664a10bca90c       /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
```
