### ISSUE TITLE
`Rackup` with `Rack-3.0.0` no longer working

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#42]
1. This Rack update seems to have broken something:
2. https://github.com/zdavatz/davaz.com/commit/d694b7fa1bf59b58adeff2360b5ccb60be41fc4c
3. Currently `Rackup` results in
```
/var/lib/gems/3.0.0/gems/rack-3.0.1/lib/rack/builder.rb:92:in `load_file': Parsing options from the first comment line is no longer supported: /var/www/davaz.com/config.ru (RuntimeError)
        from /var/lib/gems/3.0.0/gems/rack-3.0.1/lib/rack/builder.rb:67:in `parse_file'
        from /var/lib/gems/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:351:in `build_app_and_options_from_config'
        from /var/lib/gems/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:260:in `app'
        from /var/lib/gems/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:421:in `wrapped_app'
        from /var/lib/gems/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:323:in `block in start'
        from /var/lib/gems/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:379:in `handle_profiling'
        from /var/lib/gems/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:322:in `start'
        from /var/lib/gems/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:179:in `start'
        from /var/lib/gems/3.0.0/gems/rackup-0.2.3/bin/rackup:5:in `<top (required)>'
        from /usr/local/bin/rackup:25:in `load'
        from /usr/local/bin/rackup:25:in `<main>'
```

**Comment by zdavatz** [comment]
Removing the first two comment lines of the file https://github.com/zdavatz/davaz.com/blob/master/config.ru seems to helpl
