### ISSUE TITLE
bundler: failed to load command: rackup (/usr/local/bin/rackup)

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#43]
1. I am setting up Davaz.com on a new server.
2. Installed all gems with `bundle install`
3. Starting davaz.com with the following command via `deamontools`:
```
#!/bin/sh
exec 2>&1
cd /var/www/davaz.com
exec setuidgid zdavatz bundle exec rackup config.ru
```
4. Results in
```
@40000000638a25c902593434 bundler: failed to load command: rackup (/usr/local/bin/rackup)
@40000000638a25c9025ffe7c /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/rubygems_integration.rb:362:in `block in replace_bin_path': can't find executable rackup for gem rackup. rackup is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
@40000000638a25c902600e1c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/rubygems_integration.rb:390:in `block in replace_bin_path'
@40000000638a25c9026015ec       from /usr/local/bin/rackup:25:in `<top (required)>'
@40000000638a25c90265078c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:63:in `load'
@40000000638a25c902650f5c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
@40000000638a25c902651344       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:28:in `run'
@40000000638a25c90265172c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/cli.rb:494:in `exec'
@40000000638a25c902697c2c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
@40000000638a25c9026dece4       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
@40000000638a25c9026df0cc       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
@40000000638a25c9026df89c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/cli.rb:30:in `dispatch'
@40000000638a25c90272b774       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
@40000000638a25c90272c32c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/cli.rb:24:in `start'
@40000000638a25c90272cafc       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/exe/bundle:49:in `block in <top (required)>'
@40000000638a25c902780ea4       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
@40000000638a25c902781674       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/bundler-2.2.4/exe/bundle:37:in `<top (required)>'
@40000000638a25c902781a5c       from /usr/local/bin/bundle:25:in `load'
```
5. `rackup` is there in `/usr/local/bin`

**Comment by zdavatz** [comment]
this seems to solve the problem:
https://github.com/zdavatz/davaz.com/commit/3b4c88a3796e654b7c9e959babfb0c095c33b7fb
