### ISSUE TITLE
Parsing options from the first comment line is no longer supported

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#44]
1. `bundle exec rackup config.ru`
2. Results in
```
/var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.0/lib/rack/builder.rb:92:in `load_file': Parsing options from the first comment line is no longer supported: /var/www/davaz.com/config.ru (RuntimeError)
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rack-3.0.0/lib/rack/builder.rb:67:in `parse_file'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:351:in `build_app_and_options_from_config'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:260:in `app'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:421:in `wrapped_app'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:323:in `block in start'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:379:in `handle_profiling'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:322:in `start'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/lib/rackup/server.rb:179:in `start'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/rackup-0.2.3/bin/rackup:5:in `<top (required)>'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/bin/rackup:25:in `load'
        from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/bin/rackup:25:in `<main>'
```

**Comment by zdavatz** [comment]
This seems to help: 5fa82c8c5916acad0225400052a6afa5b02c9807
