### ISSUE TITLE
hpricot-0.8.6/lib/hpricot.rb:20:in `require': incompatible library version

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/davaz.com#46]
1. Running this command in `/var/www/davaz.com` works
2. `bundle exec rackup config.ru`
3. But starting with deamontools
```
zdavatz@davaz:/var/www/davaz.com$ cat /var/www/davaz.com/svc/run 
#!/bin/sh
exec 2>&1
cd /var/www/davaz.com
exec setuidgid zdavatz bundle exec rackup config.ru
```
4. Results in
```
@40000000638a35d0199faf4c bundler: failed to load command: rackup (/var/www/davaz.com/vendor/bundle/ruby/3.0.0/bin/rackup)
@40000000638a35d019a0c4a4 /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/hpricot-0.8.6/lib/hpricot.rb:20:in `require': incompatible library version - /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/hpricot-0.8.6/lib/hpricot_scan.so (LoadError)
@40000000638a35d019a1264c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/hpricot-0.8.6/lib/hpricot.rb:20:in `<top (required)>'
@40000000638a35d019a12e1c       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.0/lib/sbsm/validator.rb:33:in `require'
@40000000638a35d019a135ec       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.0/lib/sbsm/validator.rb:33:in `<top (required)>'
@40000000638a35d019a139d4       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.0/lib/sbsm/session_store.rb:35:in `require'
@40000000638a35d019a15cfc       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.0/lib/sbsm/session_store.rb:35:in `<top (required)>'
@40000000638a35d019a164cc       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.0/lib/sbsm/app.rb:29:in `require'
@40000000638a35d019a168b4       from /var/www/davaz.com/vendor/bundle/ruby/3.0.0/gems/sbsm-1.6.0/lib/sbsm/app.rb:29:in `<top (required)>'
@40000000638a35d019a18bdc       from /var/www/davaz.com/src/util/app.rb:1:in `require'
@40000000638a35d019a18fc4       from /var/www/davaz.com/src/util/app.rb:1:in `<top (required)>'
@40000000638a35d019a193ac       from /var/www/davaz.com/config.ru:5:in `require'
```

**Comment by zdavatz** [comment]
this solves the problem:
```
#!/bin/sh
exec 2>&1
cd /var/www/davaz.com
exec setuidgid zdavatz /home/zdavatz/.rbenv/versions/3.0.0/bin/bundle exec rackup config.ru
```
